/**
 * Bootstrap CSS Class Mappings
 * 
 * This file contains class name to CSS property mappings inspired by Bootstrap.
 * 
 * Bootstrap - MIT License
 * Copyright (c) 2011-2024 The Bootstrap Authors
 * https://getbootstrap.com
 * 
 * These mappings are derived from Bootstrap's publicly documented CSS classes
 * and their standard CSS equivalents. CSS class names and standard CSS properties
 * are not copyrightable - they are functional naming conventions.
 */

// Bootstrap CSS to CSS mapping library
export const bootstrapMap: Record<string, string> = {
  // Container
  'container': 'width: 100%; padding-right: 0.75rem; padding-left: 0.75rem; margin-right: auto; margin-left: auto;',
  'container-fluid': 'width: 100%; padding-right: 0.75rem; padding-left: 0.75rem; margin-right: auto; margin-left: auto;',
  
  // Display utilities
  'd-flex': 'display: flex;',
  'd-grid': 'display: grid;',
  'd-block': 'display: block;',
  'd-inline': 'display: inline;',
  'd-inline-block': 'display: inline-block;',
  'd-none': 'display: none;',
  
  // Flex utilities
  'flex-row': 'flex-direction: row;',
  'flex-column': 'flex-direction: column;',
  'flex-wrap': 'flex-wrap: wrap;',
  'flex-nowrap': 'flex-wrap: nowrap;',
  'justify-content-start': 'justify-content: flex-start;',
  'justify-content-end': 'justify-content: flex-end;',
  'justify-content-center': 'justify-content: center;',
  'justify-content-between': 'justify-content: space-between;',
  'justify-content-around': 'justify-content: space-around;',
  'align-items-start': 'align-items: flex-start;',
  'align-items-end': 'align-items: flex-end;',
  'align-items-center': 'align-items: center;',
  'align-items-baseline': 'align-items: baseline;',
  'align-items-stretch': 'align-items: stretch;',
  
  // Spacing - Margin
  'm-0': 'margin: 0;',
  'm-1': 'margin: 0.25rem;',
  'm-2': 'margin: 0.5rem;',
  'm-3': 'margin: 1rem;',
  'm-4': 'margin: 1.5rem;',
  'm-5': 'margin: 3rem;',
  'mt-0': 'margin-top: 0;',
  'mt-1': 'margin-top: 0.25rem;',
  'mt-2': 'margin-top: 0.5rem;',
  'mt-3': 'margin-top: 1rem;',
  'mt-4': 'margin-top: 1.5rem;',
  'mt-5': 'margin-top: 3rem;',
  'mb-0': 'margin-bottom: 0;',
  'mb-1': 'margin-bottom: 0.25rem;',
  'mb-2': 'margin-bottom: 0.5rem;',
  'mb-3': 'margin-bottom: 1rem;',
  'mb-4': 'margin-bottom: 1.5rem;',
  'mb-5': 'margin-bottom: 3rem;',
  'ms-0': 'margin-left: 0;',
  'ms-1': 'margin-left: 0.25rem;',
  'ms-2': 'margin-left: 0.5rem;',
  'ms-3': 'margin-left: 1rem;',
  'ms-auto': 'margin-left: auto;',
  'me-0': 'margin-right: 0;',
  'me-1': 'margin-right: 0.25rem;',
  'me-2': 'margin-right: 0.5rem;',
  'me-3': 'margin-right: 1rem;',
  'me-auto': 'margin-right: auto;',
  'mx-auto': 'margin-left: auto; margin-right: auto;',
  'my-0': 'margin-top: 0; margin-bottom: 0;',
  'my-1': 'margin-top: 0.25rem; margin-bottom: 0.25rem;',
  'my-2': 'margin-top: 0.5rem; margin-bottom: 0.5rem;',
  'my-3': 'margin-top: 1rem; margin-bottom: 1rem;',
  
  // Spacing - Padding
  'p-0': 'padding: 0;',
  'p-1': 'padding: 0.25rem;',
  'p-2': 'padding: 0.5rem;',
  'p-3': 'padding: 1rem;',
  'p-4': 'padding: 1.5rem;',
  'p-5': 'padding: 3rem;',
  'pt-0': 'padding-top: 0;',
  'pt-1': 'padding-top: 0.25rem;',
  'pt-2': 'padding-top: 0.5rem;',
  'pt-3': 'padding-top: 1rem;',
  'pt-4': 'padding-top: 1.5rem;',
  'pt-5': 'padding-top: 3rem;',
  'pb-0': 'padding-bottom: 0;',
  'pb-1': 'padding-bottom: 0.25rem;',
  'pb-2': 'padding-bottom: 0.5rem;',
  'pb-3': 'padding-bottom: 1rem;',
  'pb-4': 'padding-bottom: 1.5rem;',
  'pb-5': 'padding-bottom: 3rem;',
  'ps-0': 'padding-left: 0;',
  'ps-1': 'padding-left: 0.25rem;',
  'ps-2': 'padding-left: 0.5rem;',
  'ps-3': 'padding-left: 1rem;',
  'pe-0': 'padding-right: 0;',
  'pe-1': 'padding-right: 0.25rem;',
  'pe-2': 'padding-right: 0.5rem;',
  'pe-3': 'padding-right: 1rem;',
  'px-0': 'padding-left: 0; padding-right: 0;',
  'px-1': 'padding-left: 0.25rem; padding-right: 0.25rem;',
  'px-2': 'padding-left: 0.5rem; padding-right: 0.5rem;',
  'px-3': 'padding-left: 1rem; padding-right: 1rem;',
  'px-4': 'padding-left: 1.5rem; padding-right: 1.5rem;',
  'py-0': 'padding-top: 0; padding-bottom: 0;',
  'py-1': 'padding-top: 0.25rem; padding-bottom: 0.25rem;',
  'py-2': 'padding-top: 0.5rem; padding-bottom: 0.5rem;',
  'py-3': 'padding-top: 1rem; padding-bottom: 1rem;',
  'py-4': 'padding-top: 1.5rem; padding-bottom: 1.5rem;',
  
  // Gap (Bootstrap 5.1+)
  'gap-0': 'gap: 0;',
  'gap-1': 'gap: 0.25rem;',
  'gap-2': 'gap: 0.5rem;',
  'gap-3': 'gap: 1rem;',
  'gap-4': 'gap: 1.5rem;',
  'gap-5': 'gap: 3rem;',
  
  // Text utilities
  'text-start': 'text-align: left;',
  'text-center': 'text-align: center;',
  'text-end': 'text-align: right;',
  'text-uppercase': 'text-transform: uppercase;',
  'text-lowercase': 'text-transform: lowercase;',
  'text-capitalize': 'text-transform: capitalize;',
  'text-decoration-none': 'text-decoration: none;',
  'text-decoration-underline': 'text-decoration: underline;',
  'text-decoration-line-through': 'text-decoration: line-through;',
  'fw-light': 'font-weight: 300;',
  'fw-lighter': 'font-weight: 200;',
  'fw-normal': 'font-weight: 400;',
  'fw-medium': 'font-weight: 500;',
  'fw-semibold': 'font-weight: 600;',
  'fw-bold': 'font-weight: 700;',
  'fw-bolder': 'font-weight: 900;',
  'fst-italic': 'font-style: italic;',
  'fst-normal': 'font-style: normal;',
  'fs-1': 'font-size: calc(1.375rem + 1.5vw);',
  'fs-2': 'font-size: calc(1.325rem + 0.9vw);',
  'fs-3': 'font-size: calc(1.3rem + 0.6vw);',
  'fs-4': 'font-size: calc(1.275rem + 0.3vw);',
  'fs-5': 'font-size: 1.25rem;',
  'fs-6': 'font-size: 1rem;',
  'lh-1': 'line-height: 1;',
  'lh-sm': 'line-height: 1.25;',
  'lh-base': 'line-height: 1.5;',
  'lh-lg': 'line-height: 2;',
  
  // Background colors
  'bg-primary': 'background-color: #0d6efd;',
  'bg-secondary': 'background-color: #6c757d;',
  'bg-success': 'background-color: #198754;',
  'bg-danger': 'background-color: #dc3545;',
  'bg-warning': 'background-color: #ffc107;',
  'bg-info': 'background-color: #0dcaf0;',
  'bg-light': 'background-color: #f8f9fa;',
  'bg-dark': 'background-color: #212529;',
  'bg-white': 'background-color: #ffffff;',
  
  // Text colors
  'text-primary': 'color: #0d6efd;',
  'text-secondary': 'color: #6c757d;',
  'text-success': 'color: #198754;',
  'text-danger': 'color: #dc3545;',
  'text-warning': 'color: #ffc107;',
  'text-info': 'color: #0dcaf0;',
  'text-light': 'color: #f8f9fa;',
  'text-dark': 'color: #212529;',
  'text-white': 'color: #ffffff;',
  'text-muted': 'color: #6c757d;',
  
  // Border
  'border': 'border: 1px solid #dee2e6;',
  'border-0': 'border: 0;',
  'border-top': 'border-top: 1px solid #dee2e6;',
  'border-bottom': 'border-bottom: 1px solid #dee2e6;',
  'border-start': 'border-left: 1px solid #dee2e6;',
  'border-end': 'border-right: 1px solid #dee2e6;',
  'border-primary': 'border-color: #0d6efd;',
  'border-secondary': 'border-color: #6c757d;',
  'border-success': 'border-color: #198754;',
  'border-danger': 'border-color: #dc3545;',
  'border-warning': 'border-color: #ffc107;',
  'border-1': 'border-width: 1px;',
  'border-2': 'border-width: 2px;',
  'border-3': 'border-width: 3px;',
  'border-4': 'border-width: 4px;',
  'border-5': 'border-width: 5px;',
  'rounded': 'border-radius: 0.375rem;',
  'rounded-0': 'border-radius: 0;',
  'rounded-1': 'border-radius: 0.25rem;',
  'rounded-2': 'border-radius: 0.375rem;',
  'rounded-3': 'border-radius: 0.5rem;',
  'rounded-4': 'border-radius: 1rem;',
  'rounded-5': 'border-radius: 2rem;',
  'rounded-circle': 'border-radius: 50%;',
  'rounded-pill': 'border-radius: 50rem;',
  'rounded-top': 'border-top-left-radius: 0.375rem; border-top-right-radius: 0.375rem;',
  'rounded-bottom': 'border-bottom-left-radius: 0.375rem; border-bottom-right-radius: 0.375rem;',
  
  // Shadow
  'shadow': 'box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);',
  'shadow-sm': 'box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075);',
  'shadow-lg': 'box-shadow: 0 1rem 3rem rgba(0, 0, 0, 0.175);',
  'shadow-none': 'box-shadow: none;',
  
  // Width & Height
  'w-25': 'width: 25%;',
  'w-50': 'width: 50%;',
  'w-75': 'width: 75%;',
  'w-100': 'width: 100%;',
  'w-auto': 'width: auto;',
  'h-25': 'height: 25%;',
  'h-50': 'height: 50%;',
  'h-75': 'height: 75%;',
  'h-100': 'height: 100%;',
  'h-auto': 'height: auto;',
  
  // Position
  'position-static': 'position: static;',
  'position-relative': 'position: relative;',
  'position-absolute': 'position: absolute;',
  'position-fixed': 'position: fixed;',
  'position-sticky': 'position: sticky;',
  
  // Overflow
  'overflow-auto': 'overflow: auto;',
  'overflow-hidden': 'overflow: hidden;',
  'overflow-visible': 'overflow: visible;',
  'overflow-scroll': 'overflow: scroll;',
  
  // Components - Buttons
  'btn': 'display: inline-block; font-weight: 400; line-height: 1.5; text-align: center; text-decoration: none; vertical-align: middle; cursor: pointer; user-select: none; border: 1px solid transparent; padding: 0.375rem 0.75rem; font-size: 1rem; border-radius: 0.375rem; transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out;',
  'btn-primary': 'color: #fff; background-color: #0d6efd; border-color: #0d6efd;',
  'btn-secondary': 'color: #fff; background-color: #6c757d; border-color: #6c757d;',
  'btn-success': 'color: #fff; background-color: #198754; border-color: #198754;',
  'btn-danger': 'color: #fff; background-color: #dc3545; border-color: #dc3545;',
  'btn-warning': 'color: #000; background-color: #ffc107; border-color: #ffc107;',
  'btn-info': 'color: #000; background-color: #0dcaf0; border-color: #0dcaf0;',
  'btn-light': 'color: #000; background-color: #f8f9fa; border-color: #f8f9fa;',
  'btn-dark': 'color: #fff; background-color: #212529; border-color: #212529;',
  'btn-sm': 'padding: 0.25rem 0.5rem; font-size: 0.875rem; border-radius: 0.25rem;',
  'btn-lg': 'padding: 0.5rem 1rem; font-size: 1.25rem; border-radius: 0.5rem;',
  
  // Components - Forms
  'form-control': 'display: block; width: 100%; padding: 0.375rem 0.75rem; font-size: 1rem; font-weight: 400; line-height: 1.5; color: #212529; background-color: #fff; border: 1px solid #ced4da; border-radius: 0.375rem;',
  'form-label': 'margin-bottom: 0.5rem; font-weight: 500;',
  'form-select': 'display: block; width: 100%; padding: 0.375rem 2.25rem 0.375rem 0.75rem; font-size: 1rem; font-weight: 400; line-height: 1.5; color: #212529; background-color: #fff; border: 1px solid #ced4da; border-radius: 0.375rem;',
  'form-check': 'display: block; min-height: 1.5rem; padding-left: 1.5em; margin-bottom: 0.125rem;',
  'form-check-input': 'width: 1em; height: 1em; margin-top: 0.25em; vertical-align: top; background-color: #fff; border: 1px solid rgba(0, 0, 0, 0.25); appearance: none;',
  
  // Components - Cards
  'card': 'position: relative; display: flex; flex-direction: column; min-width: 0; word-wrap: break-word; background-color: #fff; background-clip: border-box; border: 1px solid rgba(0, 0, 0, 0.125); border-radius: 0.375rem;',
  'card-body': 'flex: 1 1 auto; padding: 1rem 1rem;',
  'card-title': 'margin-bottom: 0.5rem; font-size: 1.25rem; font-weight: 500;',
  'card-text': 'margin-bottom: 1rem;',
  'card-header': 'padding: 0.5rem 1rem; margin-bottom: 0; background-color: rgba(0, 0, 0, 0.03); border-bottom: 1px solid rgba(0, 0, 0, 0.125);',
  'card-footer': 'padding: 0.5rem 1rem; background-color: rgba(0, 0, 0, 0.03); border-top: 1px solid rgba(0, 0, 0, 0.125);',
  
  // Components - Alerts
  'alert': 'position: relative; padding: 1rem 1rem; margin-bottom: 1rem; border: 1px solid transparent; border-radius: 0.375rem;',
  'alert-primary': 'color: #084298; background-color: #cfe2ff; border-color: #b6d4fe;',
  'alert-success': 'color: #0f5132; background-color: #d1e7dd; border-color: #badbcc;',
  'alert-danger': 'color: #842029; background-color: #f8d7da; border-color: #f5c2c7;',
  'alert-warning': 'color: #664d03; background-color: #fff3cd; border-color: #ffecb5;',
  
  // Components - Badges
  'badge': 'display: inline-block; padding: 0.35em 0.65em; font-size: 0.75em; font-weight: 700; line-height: 1; color: #fff; text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: 0.375rem;',
  'bg-primary-subtle': 'background-color: #cfe2ff;',
  'bg-success-subtle': 'background-color: #d1e7dd;',
  'bg-danger-subtle': 'background-color: #f8d7da;',
  
  // Grid system
  'row': 'display: flex; flex-wrap: wrap; margin-right: -0.75rem; margin-left: -0.75rem;',
  'col': 'flex: 1 0 0%; padding-right: 0.75rem; padding-left: 0.75rem;',
  'col-1': 'flex: 0 0 auto; width: 8.333333%;',
  'col-2': 'flex: 0 0 auto; width: 16.666667%;',
  'col-3': 'flex: 0 0 auto; width: 25%;',
  'col-4': 'flex: 0 0 auto; width: 33.333333%;',
  'col-6': 'flex: 0 0 auto; width: 50%;',
  'col-8': 'flex: 0 0 auto; width: 66.666667%;',
  'col-12': 'flex: 0 0 auto; width: 100%;',
  
  // Utilities
  'text-truncate': 'overflow: hidden; text-overflow: ellipsis; white-space: nowrap;',
  'text-wrap': 'white-space: normal;',
  'text-nowrap': 'white-space: nowrap;',
  'user-select-none': 'user-select: none;',
  'pe-none': 'pointer-events: none;',
  'pe-auto': 'pointer-events: auto;',
  'visible': 'visibility: visible;',
  'invisible': 'visibility: hidden;',
  'opacity-0': 'opacity: 0;',
  'opacity-25': 'opacity: 0.25;',
  'opacity-50': 'opacity: 0.5;',
  'opacity-75': 'opacity: 0.75;',
  'opacity-100': 'opacity: 1;',
  'vstack': 'display: flex; flex-direction: column; align-self: stretch;',
  'hstack': 'display: flex; flex-direction: row; align-items: center; align-self: stretch;',
};

// Bootstrap color mapping to SCSS variables
export const bootstrapColorMap: Record<string, string> = {
  'bg-primary': '$primary',
  'bg-secondary': '$secondary',
  'bg-success': '$success',
  'bg-danger': '$danger',
  'bg-warning': '$warning',
  'bg-info': '$info',
  'bg-light': '$light',
  'bg-dark': '$dark',
  'text-primary': '$primary',
  'text-secondary': '$secondary',
  'text-success': '$success',
  'text-danger': '$danger',
  'text-warning': '$warning',
  'text-info': '$info',
  'text-light': '$light',
  'text-dark': '$dark',
};

// Bootstrap spacing mapping to SCSS variables
export const bootstrapSpacingMap: Record<string, string> = {
  'm-1': '$spacing-1',
  'm-2': '$spacing-2',
  'm-3': '$spacing-3',
  'm-4': '$spacing-4',
  'm-5': '$spacing-5',
  'mt-1': '$spacing-mt-2',
  'mt-2': '$spacing-mt-2',
  'mt-3': '$spacing-mt-3',
  'mb-1': '$spacing-mb-2',
  'mb-2': '$spacing-mb-2',
  'mb-3': '$spacing-mb-4',
  'p-1': '$spacing-1',
  'p-2': '$spacing-2',
  'p-3': '$spacing-3',
  'p-4': '$spacing-4',
  'p-5': '$spacing-5',
  'gap-1': '$spacing-gap-1',
  'gap-2': '$spacing-gap-3',
  'gap-3': '$spacing-gap-4',
};
